import Head from "next/head";
import { Auth } from "./auth/auth";

export default function Home() {
  return (
    <>
      <Head>
        <title>Antojitos El Cochecito</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Auth />

    </>
  );
}
